services:
    postgress:
        image: postgres:16.1
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: typeormstudy
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

volumes:
    postgres:
